### ISSUE TITLE
False warning about JS support on login

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#599]
Am I the only one who is annoyed by this flashing yellow "JAVASCRIPT_REQ + INCOMPAT_BROWSER + MODERN_BROWSER + Browser !Supported" message at the beginning of logging in? :)

This appears to me in Chrome and Opera.

New users might be worried about this.

**Comment by juek** [comment]
> Am I the only one who is annoyed by this flashing yellow "JAVASCRIPT…

You're not alone! I just fixed it – will push it later.

**Comment by juek** [comment]
Should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/e43ce27b6bed6cc1081326f7ae077c185ed3aee1)

**Comment by mahotilo** [comment]
Works great. 
And the integrated HideUI is also charming!

**Comment by juek** [comment]
> And the integrated HideUI is also charming!

BTW: Could you please test keyboard shortcuts with cyrillic keyboard?

**Comment by mahotilo** [comment]
1. Ctrl+h - works
2. Ctrl+р ("р" is Cyrillic letter in place of "h") - does not work
3. Changing Keyboard Shortcut to Ctrl+р 

Ctrl+р - still does not work
Console messages

>  (index):117 Uncaught SyntaxError: Unexpected token ';'
> admin.js?v=5.1.1-b1:918 Uncaught ReferenceError: isadmin is not defined
>     at HTMLDocument.<anonymous> (admin.js?v=5.1.1-b1:918)
>     at i (jquery.js?v=5.1.1-b1:2)
>     at Object.fireWith [as resolveWith] (jquery.js?v=5.1.1-b1:2)
>     at Function.ready (jquery.js?v=5.1.1-b1:2)
>     at HTMLDocument.J (jquery.js?v=5.1.1-b1:2)

Broken layout
![image](https://user-images.githubusercontent.com/14929385/75910409-7e74be80-5e56-11ea-8842-861c245247ee.png)

Also. Opera has conflict with Ctrl+H Shortcut, which by default is associated with History.

**Comment by juek** [comment]
> BTW: Could you please test keyboard shortcuts with cyrillic keyboard?

Before you brick your setup, get [this commit](https://github.com/Typesetter/Typesetter/commit/d23ee36a39fd3055dee06cb20efc7dc13d203129) first … oops, too late :)

**Comment by mahotilo** [comment]
> Before you brick your setup

I was still able to type ctrl+h in input:)

**Comment by juek** [comment]
> Also. Opera has conflict with Ctrl+H Shortcut, which by default is associated with History.

Same with Firefox, history panel should be prevented when Ctrl + h is used by HideAdminUI


We're OT, should we open a separate issue?

**Comment by mahotilo** [comment]
Last fix works for me.

**Comment by juek** [comment]
> Last fix works for me.

Awesome!

**Comment by mahotilo** [comment]
I have made a new issue:)
https://github.com/Typesetter/Typesetter/issues/602
